name: Backend CI
on:
    push:
        branches:
            - main
    workflow_dispatch:
    pull_request:
        branches:
            - main
jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Init submodules
              run: git submodule update --init --recursive
            - name: Cache the dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: node_modules
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install the dependencies
              if: failure() || steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Verify the cache
              if: success() && steps.cache.outputs.cache-hit == 'true'
              run: echo "Cache restored successfully"
            - name: Lint code
              run: npm run lint
    Test:
        needs: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Init submodules
              run: git submodule update --init --recursive
            - name: Cache the dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: node_modules
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install the dependencies
              if: failure() || steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Verify the cache
              if: success() && steps.cache.outputs.cache-hit == 'true'
              run: echo "Cache restored successfully"
            - name: Validate API contracts
              run: npx swagger-cli validate ./project_contracts/openapi.yml
            - name: Run tests
              run: npm run test
            - name: Debug - Check Secrets
              run: |
                    echo "Username: ${{ secrets.DOCKER_USERNAME }}"
                    echo "Token length: ${{ secrets.DOCKER_TOKEN }}"
    Deploy:
        needs: Test
        uses: ./.github/workflows/deploy.yml
        
    print_result:
        needs: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Print Deploy Result
              run: |
                echo "Deploy Result: ${{ needs.Deploy.outputs.result }}"

