name: Backend Deploy
on: 
    workflow_call:
        outputs:
            result:
                description: 'Result of the deploy step'
                value: ${{ jobs.Deploy.outputs.resultss }}

jobs:
    Deploy:
        environment: testing
        outputs:
            resultss: ${{ steps.result.outputs.step-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Init submodules
              run: git submodule update --init --recursive
            - name: Debug - Check Secrets
              run: |
                    echo "Username: ${{ secrets.DOCKER_USERNAME }}"
                    echo "Token length: ${{ secrets.DOCKER_TOKEN }}"
            - name: Login to docker
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
            - name: Build and Push Docker Image
              run: |
                    docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .
                    docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
            - name: Logout from Docker Hub
              if: always()
              run: docker logout
            - name: Deploy to Server
              run: echo "Pushed to docker hub"
            - name: Set result output
              id: result
              run: echo "step-result=success">>$GITHUB_OUTPUT