name: Backend Deploy
on: 
    workflow_call:
        inputs:
            DOCKER_USERNAME:
                description: 'Docker Hub username'
                required: true
                type: string
            DOCKER_TOKEN:
                description: 'Docker Hub token'
                required: true
                type: string
                
        outputs:
            result:
                description: 'Result of the deploy step'
                value: ${{ jobs.Deploy.outputs.resultss }}

jobs:
    Deploy:
        outputs:
            resultss: ${{ steps.result.outputs.step-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Init submodules
              run: git submodule update --init --recursive
            - name: Login to docker
              uses: docker/login-action@v3
              with:
                  username: ${{ inputs.DOCKER_USERNAME }}
                  password: ${{ inputs.DOCKER_TOKEN }}
            - name: Build and Push Docker Image
              run: |
                    docker build -t ${{ inputs.DOCKER_USERNAME }}/backend:latest .
                    docker push ${{ inputs.DOCKER_USERNAME }}/backend:latest
            - name: Logout from Docker Hub
              if: always()
              run: docker logout
            - name: Deploy to Server
              run: echo "Pushed to docker hub"
            - name: Set result output
              id: result
              run: echo "step-result=success">>$GITHUB_OUTPUT